### ISSUE TITLE
[PE-D] add_meeting command

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2113-T11-3/tp#192]
![image.png](https://raw.githubusercontent.com/OzairHasan/ped/main/files/be70c7fa-bdd3-4a1b-a5ae-dc3ad8e6f9d4.png)

I gave an extra parameter which was the name of a user when adding a new meeting. Instead of telling me to remove the name parameter, I get a message that 1 or more parameters is further required. 

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: OzairHasan/ped#3

**Comment by ibrahimisramos** [comment]
Thanks for this!
