### ISSUE TITLE
[PE-D] Delete event command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2113-T11-3/tp#193]
![image.png](https://raw.githubusercontent.com/OzairHasan/ped/main/files/0202c628-af6c-4617-94f1-d068cc09a8d5.png)

Conflicting instructions in format and example of usage.

-------------
Labels: `type.DocumentationBug` `severity.High`
original: OzairHasan/ped#4

**Comment by ibrahimisramos** [comment]
Thanks for pointing this out!
