### ISSUE TITLE
[PE-D] Unexpected program crash

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2113-T11-3/tp#204]
![image.png](https://raw.githubusercontent.com/GlendonNotGlen/ped/main/files/bed4499a-00a3-4eb0-a7d8-88068a02fbb8.png)

Similar to earlier crash, program crashes when a lesson is within 0000 to 0800 and calling free command

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: GlendonNotGlen/ped#5

**Comment by angyongming** [comment]
Thanks for spotting my mistake! All rectified now :)
