### ISSUE TITLE
[PE-D] Missing fullstop in error message

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2113-T11-3/tp#207]
![image.png](https://raw.githubusercontent.com/GlendonNotGlen/ped/main/files/a4ab1362-9260-459d-bc35-316c2e5513ce.png)

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: GlendonNotGlen/ped#6

**Comment by ibrahimisramos** [comment]
Add fullstop to all error messages
