### ISSUE TITLE
[PE-D] Incorrect help description for list command family format

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2113-T11-3/tp#208]
For example, the current help description for list is `list [user]`, when instead it is `list n/[User]` that actually works. The format also does not seem to be on the UG either.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: ngys117/ped#6

**Comment by ibrahimisramos** [comment]
Add more specific in the user guide that the n/ is the parameter and should not be included in the value
