### ISSUE TITLE
[PE-D] Non accepted Day input was accepted

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2113-T11-3/tp#209]
![image.png](https://raw.githubusercontent.com/GlendonNotGlen/ped/main/files/285a5e12-6593-4cee-a5fc-87e2591f8414.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: GlendonNotGlen/ped#7

**Comment by ibrahimisramos** [comment]
Its a good implementation to safeguard against typos!
