### ISSUE TITLE
Code Review - Yong Ming

### ISSUE THREAD

**Issue by swongts** [AY2122S2-CS2113-T11-3/tp#212]
**Timetable.java**
 
![image](https://user-images.githubusercontent.com/70316271/161410752-aeecb49f-3ca6-47e8-9a77-57d4f1856c82.png)

This part could have been structured better, perhaps a Boolean function can be created since the if condition is long and confusing to read. Perhaps structuring it as “if (valid condition)” would be more intuitive for the reader.

**ListCommand.java**
 
![image](https://user-images.githubusercontent.com/70316271/161410775-a848e7aa-dafc-4202-9d6c-c4686017f264.png)

You can consider throwing an exception here when string length == 0 and catching it at execute.

Overall, good practice of SLAP and very neat code.

**Comment by angyongming** [comment]
Thanks samantha! I've made the necessary changes alr :)
